### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'profiles'

### ISSUE THREAD

**Issue by Matypetzold** [jpvantassel/swprepost#12] opened 2024-10-03 17:39 UTC
I don't know how to proceed with the usage of the code. I am getting the following error:
![Error](https://github.com/user-attachments/assets/ab6bc124-eb4f-40f2-88a1-3aaf6b74f82c)

**Comment by jpvantassel** [comment] 2024-10-09 20:32
Duplicate of #11
Please do not create duplicate issues.

**Closed as not planned by jpvantassel** 2024-10-09 20:32 UTC
