### ISSUE TITLE
Error when executing the inversion locally 

### ISSUE THREAD

**Issue by Valdebenit0** [jpvantassel/swprepost#14] opened 2024-10-21 23:10 UTC
I manage to load the .param files and the .target file to dinver, however I have problems when exporting the DC and GM text files, as they do not contain the structure that allows the code to read it in the case of GM and as for DC I am unable to export them in text format.
I would be very grateful if someone could explain me in detail how you ran your local inversion, which version of dinver you used and how you exported the GM and DC files in text format.

**Comment by jpvantassel** [comment] 2024-10-23 21:48
Hi @Valdebenit0,

This question is a duplicate of #13. Your question is a geopsy-related rather than swprepost-related. swprepost was designed to interface with Geopsy and so an understanding of Geopsy is necessary, although the use of swbatch somewhat avoids this requirement. See the answer to #13 for more information on what to do next.

**Closed as completed by jpvantassel** 2024-10-23 21:48 UTC
